version: '2.2'
services:
  client:
    build: ./client
    depends_on:
      server:
        condition: service_healthy
    environment:
      HOSTNAME: http://server:3000
      INTERVAL: 1
    cpus: '0.1'
    mem_limit: 10000000
  server:
    build: ./server
    depends_on:
      external:
        condition: service_healthy
    environment:
      EXTERNAL_HOST_NAME: http://external:3000
    cpus: '0.1'
    mem_limit: 10000000
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/health"]
  external:
    build: ./external
    environment:
      DELAY: 3000
    cpus: '0.1'
    mem_limit: 10000000
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/health"]